apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bootc
spec:

  workspaces:
  - name: source-workspace
  - name: registry-token
    optional: true
  - name: caches
    optional: true
  - name: entitlements
    optional: true
  - name: git-auth
    optional: true
  - name: registries-conf
    optional: true
  - name: rclone-config
    optional: true

  params:
  - name: git-url
    type: string
  - name: git-revision
    type: string
    default: main
  - name: bootc-image-name
    type: string
  - name: app-image-name
    type: string
  - name: rclone-model-src
    type: string
  - name: rclone-model-dest
    type: string
  - name: build-architectures
    type: array
  - name: pypi-mirror-url
    type: string
    default: ""

  tasks:

  - name: clone-repo
    taskRef:
      kind: Task
      name: git-clone
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: source-workspace
    - name: basic-auth
      workspace: git-auth

  - name: fetch-model
    runAfter: ["clone-repo"]
    taskRef:
      kind: Task
      name: rclone
    params:
    - name: rclone-src
      value:
      - $(params.rclone-model-src)
    - name: rclone-dest
      value: $(params.rclone-model-dest)
    workspaces:
    - name: source-workspace
      workspace: source-workspace
    - name: rclone-config
      workspace: rclone-config

  - name: buildah-app
    runAfter: ["fetch-model"]
    taskRef:
      name: buildah
    params:
    - name: image-name
      value: $(params.app-image-name)
    - name: context-dir
      value: app
    - name: containerfile-path
      value: app/Containerfile
    - name: build-architectures
      value:
      - $(params.build-architectures)
    - name: pypi-mirror-url
      value: $(params.pypi-mirror-url)
    workspaces:
    - name: source-workspace
      workspace: source-workspace
    - name: dockerconfig
      workspace: registry-token

  - name: buildah-bootc
    runAfter: ["buildah-app"]
    taskRef:
      name: buildah
    params:
    - name: image-name
      value: $(params.bootc-image-name)
    - name: context-dir
      value: bootc
    - name: containerfile-path
      value: bootc/Containerfile
    - name: build-architectures
      value:
      - $(params.build-architectures)
    workspaces:
    - name: source-workspace
      workspace: source-workspace
    - name: dockerconfig
      workspace: registry-token
    - name: caches
      workspace: caches
    - name: entitlements
      workspace: entitlements
