FROM quay.io/nmasse-redhat/jetpack-multiarch:r36.4.0

ADD *.py *.jpg *.onnx /opt/app
WORKDIR /opt/app
RUN <<EOF
set -Eeu
apt update
DEBIAN_FRONTEND=noninteractive apt install -y git python3-pip
rm -rf /var/lib/apt/lists/*
apt-get clean
pip3 install -y onnxruntime_gpu
pip3 install -r requirements.txt
EOF

ENTRYPOINT [ "python3", "app.py" ]
CMD [ ]
