apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bootc-caches
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: efs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bootc-entitlements
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: efs-csi
